"""sensor_readings

Revision ID: 5934a177ae0a
Revises: 28075874ce60
Create Date: 2026-10-06 14:51:08.855467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5934a177ae0a'
down_revision: Union[str, Sequence[str], None] = '28075874ce60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor_readings',
    sa.Column('id', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('device_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sensor_readings_device_id_recorded_at', 'sensor_readings', ['device_id', sa.literal_column('recorded_at DESC')], unique=False)
    op.add_column('devices', sa.Column('sampling_interval_seconds', sa.Integer(), server_default=sa.text('300'), nullable=False))
    op.add_column('devices', sa.Column('tracking_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###

    # Backfill: copy sampling_interval_seconds from default_config when it is a number.
    op.execute("""
        UPDATE devices
        SET sampling_interval_seconds = (default_config->>'sampling_interval_seconds')::numeric::int
        WHERE jsonb_typeof(default_config->'sampling_interval_seconds') = 'number'
    """)
    # Protocol values the Phase 5 selector understands: "simulation" or "mqtt".
    op.execute("""
        UPDATE devices SET default_config = jsonb_set(default_config, '{protocol}', '"simulation"')
        WHERE default_config->>'protocol' = 'sim'
    """)
    op.execute("""
        UPDATE devices SET default_config = jsonb_set(default_config, '{protocol}', '"mqtt"')
        WHERE default_config->>'protocol' = 'gpio-stub'
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # Undo the protocol rename.
    op.execute("""
        UPDATE devices SET default_config = jsonb_set(default_config, '{protocol}', '"sim"')
        WHERE default_config->>'protocol' = 'simulation'
    """)
    op.execute("""
        UPDATE devices SET default_config = jsonb_set(default_config, '{protocol}', '"gpio-stub"')
        WHERE default_config->>'protocol' = 'mqtt'
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'tracking_enabled')
    op.drop_column('devices', 'sampling_interval_seconds')
    op.drop_index('ix_sensor_readings_device_id_recorded_at', table_name='sensor_readings')
    op.drop_table('sensor_readings')
    # ### end Alembic commands ###